---@class e_buff_type
---@field public internal number
---@field public aura number
---@field public combat_enchancer number
---@field public combat_dehancer number
---@field public spell_shield number
---@field public stun number
---@field public invisibility number
---@field public silence number
---@field public taunt number
---@field public berserk number
---@field public polymorph number
---@field public slow number
---@field public snare number
---@field public damage number
---@field public heal number
---@field public haste number
---@field public spell_immunity number
---@field public physical_immunity number
---@field public invulnerability number
---@field public attack_speed_slow number
---@field public near_sight number
---@field public currency number
---@field public fear number
---@field public charm number
---@field public poison number
---@field public suppression number
---@field public blind number
---@field public counter number
---@field public shred number
---@field public flee number
---@field public knockup number
---@field public knockback number
---@field public disarm number
---@field public grounded number
---@field public drowsy number
---@field public asleep number
---@field public obscured number
---@field public clickproof_to_enemies number
---@field public un_killable number
---@field public unknown number
local e_buff_type = {}

---@type e_buff_type
_G.e_buff_type = {}